version: '3.3'

services:
  web:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data: